name: frac_env
channels:
  - defaults
dependencies:
  - python=3.7.7
  - pip
  - pip:
    - matplotlib==3.3.1
    - mplstereonet==0.6.2
    - numpy==1.19.1
    - pandas==1.1.1
    - scipy==1.5.2
    - seaborn==0.10.1
    - watermark==2.0.2
